# Generated by Django 4.2.21 on 2025-07-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa de la especie', null=True, upload_to='especies/'),
        ),
    ]
