# Generated by Django 4.2.21 on 2025-07-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_especie_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada de la especie'),
        ),
    ]
